# Generated by Django 5.1.3 on 2024-11-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_app1post_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App1Post',
        ),
    ]
